main: tk.halfaheart.core.HalfAHeart
name: HalfAHeart
version: ${project.version}
api-version: '1.15'
commands:
  sign:
    description: Set the RTP sign
    permission: halfaheart.sign
  test:
    description: test plugin for testing
    permission: halfaheart.test